In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [8]:
# from google.colab import files
# upload = files.upload()

In [9]:
data=pd.read_csv('/content/Social_Network_Ads.csv')
data.head(5)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [10]:
data_x=data.iloc[:,[2,3]].values
data_y=data.iloc[:,4].values

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train, y_test=train_test_split(data_x,data_y,test_size=0.3,random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler() # Classification

In [13]:
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [14]:
from sklearn.linear_model import LogisticRegression
cls=LogisticRegression(random_state=0)
cls.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [15]:
y_pred=cls.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1])

In [16]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1])

In [17]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_pred)
cm

array([[75,  4],
       [ 9, 32]])

In [18]:
from sklearn.metrics import accuracy_score

In [19]:
ac= accuracy_score(y_test, y_pred)
ac

0.8916666666666667