In [1]:
import pandas as pd
import numpy as np

In [2]:
#pwd

In [4]:
path = "/content/taxi.csv"
data = pd.read_csv(path)

In [5]:
print(data.head())
print(data.tail())
len(data)

   Priceperweek  Population  ...  Averageparkingpermonth  Numberofweeklyriders
0            15     1800000  ...                      50                192000
1            15     1790000  ...                      50                190400
2            15     1780000  ...                      60                191200
3            25     1778000  ...                      60                177600
4            25     1750000  ...                      60                176800

[5 rows x 5 columns]
    Priceperweek  Population  ...  Averageparkingpermonth  Numberofweeklyriders
22            86     1590000  ...                     165                126240
23            98     1595000  ...                     175                123888
24            87     1590000  ...                     175                126080
25            77     1600000  ...                     190                151680
26            63     1610000  ...                     200                152800

[5 rows x 5 columns]


27

In [6]:
data_x=data.iloc[:, 0:-1].values
data_y=data.iloc[:,-1]

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
train_test_split(data_x, data_y, test_size=0.3, random_state=0)

[array([[     75, 1615000,   14010,     150],
        [     65, 1640000,   12650,     105],
        [     15, 1790000,    6200,      50],
        [     30, 1710000,    9630,      80],
        [     63, 1610000,   16200,     200],
        [     77, 1600000,   16000,     190],
        [     30, 1720000,    8800,      75],
        [     25, 1725000,    8200,      75],
        [     25, 1750000,    6550,      60],
        [     75, 1630000,   13224,     125],
        [     30, 1705000,    9200,      80],
        [     30, 1725000,    8600,      75],
        [     86, 1590000,   15000,     165],
        [     25, 1778000,    6500,      60],
        [     15, 1800000,    5800,      50],
        [     80, 1605000,   14468,     155],
        [     40, 1630000,   11830,     105],
        [     40, 1695000,   11330,      85]]),
 array([[     15, 1780000,    6400,      60],
        [     87, 1590000,   15600,     175],
        [     40, 1690000,   11800,     105],
        [    102, 1635000,   130

In [9]:
x_train, x_test, y_train, y_test  = train_test_split(data_x, data_y, test_size=0.3, random_state=0)

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
reg=LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [12]:
y_pred=reg.predict(x_test)
y_pred # Prints predicted value

array([188629.50339543, 136559.39301861, 167923.33044203, 126048.35876704,
       178953.09696641, 166223.49873765, 130975.62779069, 167971.3136973 ,
       141866.03727522])

In [13]:
y_test # Shows Actual Value

2     191200
24    126080
14    160800
17    115696
5     178400
11    163200
23    123888
13    161600
19    150400
Name: Numberofweeklyriders, dtype: int64

In [14]:
print(reg.coef_) # Prints coefficient values ie. b1,b2,b3,b4
print(reg.coef_[0])

[-5.68775893e+02  1.30158909e-01 -5.49376209e-02  1.22759763e+02]
-568.7758928010779


In [15]:
print(reg.intercept_) # Prints intercept values i.e b0

-41535.70104645021


In [16]:
# y= b0 + b1x1+ b2x2 + b3x3 + b4x4

y_0= reg.intercept_+reg.coef_[0]*x_test[0][0]+reg.coef_[1]*x_test[0][1]+reg.coef_[2]*x_test[0][2]+reg.coef_[3]*x_test[0][3]
y_1= reg.intercept_+reg.coef_[0]*x_test[1][0]+reg.coef_[1]*x_test[1][1]+reg.coef_[2]*x_test[1][2]+reg.coef_[2]*x_test[1][3]

In [17]:
y_1

115066.82046491446